-- MySQL Script generated by MySQL Workbench
-- Wed Apr  6 09:32:22 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Clients` ;

-- IL FAUT AVOIR 5 CHAMPS SUPPLEMENTAIRES
CREATE TABLE IF NOT EXISTS `mydb`.`Clients` (
  `id_Client` INT NOT NULL,
  -- INSERER ICI LES CHAMPS SUPPLEMENTAIRES
  PRIMARY KEY (`id_Client`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fournisseurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Fournisseurs` ;

-- IL FAUT AVOIR 5 CHAMPS SUPPLEMENTAIRES
CREATE TABLE IF NOT EXISTS `mydb`.`Fournisseurs` (
  `id_Fournisseur` INT NOT NULL,
  -- INSERER ICI LES CHAMPS SUPPLEMENTAIRES
  PRIMARY KEY (`id_Fournisseur`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`LEGO_Themes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LEGO_Themes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`LEGO_Themes` (
  `id_Theme` INT NOT NULL,
  `LEGO_Themescol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Theme`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LEGO_Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LEGO_Categories` ;

CREATE TABLE IF NOT EXISTS `mydb`.`LEGO_Categories` (
  `id_Categorie` INT NOT NULL,
  `LEGO_Categoriescol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Categorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LEGO_Couleurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LEGO_Couleurs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`LEGO_Couleurs` (
  `id_Couleur` INT NOT NULL,
  `LEGO_Couleurscol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Couleur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Magasins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Magasins` ;

-- IL FAUT AVOIR 5 CHAMPS SUPPLEMENTAIRES
CREATE TABLE IF NOT EXISTS `mydb`.`Magasins` (
  `id_Magasin` INT NOT NULL,
  -- INSERER ICI LES CHAMPS SUPPLEMENTAIRES
  PRIMARY KEY (`id_Magasin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LEGO_Pieces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LEGO_Pieces` ;

CREATE TABLE IF NOT EXISTS `mydb`.`LEGO_Pieces` (
  `idLEGO_Pieces` INT NOT NULL,
  `Nom_piece` VARCHAR(45) NOT NULL,
  `id_Categorie` INT NOT NULL,
  PRIMARY KEY (`idLEGO_Pieces`, `id_Categorie`),
  INDEX `id_Categorie_idx` (`id_Categorie` ASC) VISIBLE,
  CONSTRAINT `id_Categorie`
    FOREIGN KEY (`id_Categorie`)
    REFERENCES `mydb`.`LEGO_Categories` (`id_Categorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LEGO_Sets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LEGO_Sets` ;

CREATE TABLE IF NOT EXISTS `mydb`.`LEGO_Sets` (
  `id_Set` INT NOT NULL,
  `id_Piece` INT NOT NULL,
  `Quantite_Piece` INT NOT NULL,
  `id_Theme` INT NOT NULL,
  `id_Couleur` INT NOT NULL,
  PRIMARY KEY (`id_Set`, `id_Piece`, `id_Theme`, `id_Couleur`),
  INDEX `id_Piece_idx` (`id_Piece` ASC) VISIBLE,
  INDEX `id_Theme_idx` (`id_Theme` ASC) VISIBLE,
  INDEX `id_Couleur_idx` (`id_Couleur` ASC) VISIBLE,
  CONSTRAINT `id_Piece`
    FOREIGN KEY (`id_Piece`)
    REFERENCES `mydb`.`LEGO_Pieces` (`idLEGO_Pieces`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_Theme`
    FOREIGN KEY (`id_Theme`)
    REFERENCES `mydb`.`LEGO_Themes` (`id_Theme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_Couleur`
    FOREIGN KEY (`id_Couleur`)
    REFERENCES `mydb`.`LEGO_Couleurs` (`id_Couleur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Stock` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Stock` (
  `id_Magasin` INT NOT NULL,
  `id_Set` INT NOT NULL,
  `Quantite_Stock` INT NOT NULL,
  `Prix_Stock` DECIMAL(25) NOT NULL,
  PRIMARY KEY (`id_Magasin`, `id_Set`),
  INDEX `id_Set_idx` (`id_Set` ASC) VISIBLE,
  CONSTRAINT `id_Set`
    FOREIGN KEY (`id_Set`)
    REFERENCES `mydb`.`LEGO_Sets` (`id_Set`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_Magasin`
    FOREIGN KEY (`id_Magasin`)
    REFERENCES `mydb`.`Magasins` (`id_Magasin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employés`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Employés` ;

-- IL FAUT AVOIR 5 CHAMPS SUPPLEMENTAIRES
CREATE TABLE IF NOT EXISTS `mydb`.`Employés` (
  `id_Employe` INT NOT NULL,
  -- INSERER ICI LES CHAMPS SUPPLEMENTAIRES
  `id_Magasin` INT NOT NULL,
  PRIMARY KEY (`id_Employe`, `id_Magasin`),
  INDEX `id_Magasin_idx` (`id_Magasin` ASC) VISIBLE,
  CONSTRAINT `id_Magasin`
    FOREIGN KEY (`id_Magasin`)
    REFERENCES `mydb`.`Magasins` (`id_Magasin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Commandes Fournisseurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Commandes Fournisseurs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Commandes Fournisseurs` (
  `id_Commande_four` INT NOT NULL,
  `Commandes Fournisseurscol` VARCHAR(45) NOT NULL,
  `id_Fournisseur` INT NOT NULL,
  `id_Set` INT NOT NULL,
  PRIMARY KEY (`id_Commande_four`, `id_Fournisseur`, `id_Set`),
  INDEX `id_Fournisseur_idx` (`id_Fournisseur` ASC) VISIBLE,
  INDEX `id_Set_idx` (`id_Set` ASC) VISIBLE,
  CONSTRAINT `id_Fournisseur`
    FOREIGN KEY (`id_Fournisseur`)
    REFERENCES `mydb`.`Fournisseurs` (`id_Fournisseur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_Set`
    FOREIGN KEY (`id_Set`)
    REFERENCES `mydb`.`LEGO_Sets` (`id_Set`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Commandes Clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Commandes Clients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Commandes Clients` (
  `id_Commande_cli` INT NOT NULL,
  `Commandes Clientscol` VARCHAR(45) NOT NULL,
  `id_Client` INT NOT NULL,
  `id_Set` INT NOT NULL,
  PRIMARY KEY (`id_Commande_cli`, `id_Client`, `id_Set`),
  INDEX `id_Client_idx` (`id_Client` ASC) VISIBLE,
  INDEX `id_Set_idx` (`id_Set` ASC) VISIBLE,
  CONSTRAINT `id_Client`
    FOREIGN KEY (`id_Client`)
    REFERENCES `mydb`.`Clients` (`id_Client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_Set`
    FOREIGN KEY (`id_Set`)
    REFERENCES `mydb`.`LEGO_Sets` (`id_Set`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Livraisons magasins clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Livraisons magasins clients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Livraisons magasins clients` (
  `id_Commande_cli` INT NOT NULL,
  `id_Magasin` INT NOT NULL,
  PRIMARY KEY (`id_Commande_cli`, `id_Magasin`),
  INDEX `id_Magasin_idx` (`id_Magasin` ASC) VISIBLE,
  CONSTRAINT `id_Commande_cli`
    FOREIGN KEY (`id_Commande_cli`)
    REFERENCES `mydb`.`Commandes Clients` (`id_Commande_cli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_Magasin`
    FOREIGN KEY (`id_Magasin`)
    REFERENCES `mydb`.`Magasins` (`id_Magasin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Livraisons magasins fournisseurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Livraisons magasins fournisseurs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Livraisons magasins fournisseurs` (
  `id_Commande_four` INT NOT NULL,
  `id_Magasin` INT NOT NULL,
  PRIMARY KEY (`id_Commande_four`, `id_Magasin`),
  INDEX `id_Magasin_idx` (`id_Magasin` ASC) VISIBLE,
  CONSTRAINT `id_Commande_four`
    FOREIGN KEY (`id_Commande_four`)
    REFERENCES `mydb`.`Commandes Fournisseurs` (`id_Commande_four`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_Magasin`
    FOREIGN KEY (`id_Magasin`)
    REFERENCES `mydb`.`Magasins` (`id_Magasin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
