INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2420, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3023, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3710, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4287, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6157, 'Wheel Base');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6636, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (41854, 'Transportation Means, Vehicles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3031, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (50951, 'Tyres And Rims For Snap Ø3,2');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (51719, 'Tyres And Rims For Snap Ø3,2');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (50947, 'Transportation Means, Vehicles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (61409, 'Decoration Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (60212, 'Transportation Means, Vehicles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (93606, 'Bricks With Bows And Arches');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (12825, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3795, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3022, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (50746, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30070, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6126, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30057, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30039, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2419, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3832, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30602, 'Decoration Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (43722, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (43723, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (54383, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (54384, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (54200, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (51739, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (43719, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (92593, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (93273, 'Bricks With Bows And Arches');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (99206, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (15068, 'Bricks With Bows And Arches');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6562, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (10247, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3020, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4477, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2817, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3034, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (61184, 'Miscellaneous Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (59900, 'Bricks, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (58176, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (47904, 'Decoration Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6225, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3021, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3957, 'Signs, Flags And Poles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4349, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (55641, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (41005, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (42925, 'Bricks, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (74169, 'Decoration Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3708, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (73200, 'Figure Parts');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (73081, 'Transportation Means, Vehicles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3001, 'Bricks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3666, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3709, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2540, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (44237, 'Bricks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (11477, 'Bricks With Bows And Arches');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (37352, 'Bricks With Bows And Arches');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (35299, 'Windscreens And Cockpits');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (14918, 'Bricks, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (76382, 'Figure Parts');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (45598, 'Figure, Head Clothing');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2432, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3659, 'Bricks With Bows And Arches');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3899, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (85984, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (15207, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (43888, 'Bricks, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (10314, 'Bricks With Bows And Arches');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (15535, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (25994, 'Foodstuff');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (26603, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (33243, 'Bricks With Bows And Arches');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (78208, 'Figure Parts');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (78209, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (78211, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (78212, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3004, 'Bricks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3069, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4599, 'Interior');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (60478, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6020, 'Fences And Ladders');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (18646, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (78220, 'Animals And Creatures');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (22888, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2412, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30162, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3039, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (23893, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (26823, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (39683, 'Bricks, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3960, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (59121, 'Interior');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (78215, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (78221, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3958, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4740, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3963, 'Transportation Means, Aviation');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (48336, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6182, 'Bricks With Bows And Arches');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (15573, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (16091, 'Transportation Means, Vehicles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (22885, 'Bricks, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (28802, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (65458, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (74166, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (74214, 'Tyres And Rims, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (66118, 'Wheel Base');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (35160, 'Windscreens And Cockpits');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (28659, 'Decoration Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (35386, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (28701, 'Bricks, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (28618, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (35395, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (35390, 'Bricks, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (35378, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4079, 'Interior');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (93160, 'Foodstuff');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (28921, 'Signs, Flags And Poles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (34816, 'Bricks, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2653, 'Bricks, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3002, 'Bricks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3009, 'Bricks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3024, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3460, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3622, 'Bricks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3665, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3937, 'Functional Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6141, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6134, 'Functional Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (48729, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (62810, 'Figure, Wigs');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (87081, 'Bricks, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (92280, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (76116, 'Figure Accessories, Upper And Lower Part');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (15391, 'Functional Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (18649, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (15403, 'Functional Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (32062, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2780, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30414, 'Bricks, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4274, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (43093, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6558, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (96874, 'Miscellaneous Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3062, 'Bricks, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (63868, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (32028, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (19888, 'Textiles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (88283, 'Figure, Wigs');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6541, 'Bricks, Special Ø4.85 Hole And Connecting Bush');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2431, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30136, 'Bricks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3005, 'Bricks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6111, 'Bricks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3033, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3032, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30357, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4460, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (50950, 'Bricks With Bows And Arches');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3839, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6003, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (57894, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (87079, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (61252, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (92099, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4150, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (95199, 'Figure, Weapons');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (99780, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (15392, 'Functional Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (15712, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6632, 'Half Beams');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (18654, 'Beams');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (10907, 'Figure, Head Clothing');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (20628, 'Figure, Head Clothing');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (10337, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (20994, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (87989, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2454, 'Bricks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3003, 'Bricks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3010, 'Bricks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3176, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3297, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3298, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3831, 'Functional Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4032, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4286, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6112, 'Bricks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3038, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3895, 'Bricks, Special Ø4.85 Hole And Connecting Bush');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (48092, 'Bricks, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (60474, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6564, 'Bricks, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6565, 'Bricks, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (64567, 'Figure, Weapons');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (63864, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (60897, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (92950, 'Bricks With Bows And Arches');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (87620, 'Bricks, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (99781, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (75904, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3830, 'Functional Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (11476, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (61485, 'Functional Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (14716, 'Bricks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (60596, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (14395, 'Bricks With Bows And Arches');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (19954, 'Functional Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (87926, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (25699, 'Signs, Flags And Poles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (31493, 'Bricks, Special Ø4.85 Hole And Connecting Bush');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (60675, 'Tubes');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (20629, 'Figure, Head Clothing');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (20945, 'Figure Parts');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (15470, 'Foodstuff');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (21137, 'Figure Parts');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30002, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30068, 'Bricks, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (18663, 'Functional Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (21135, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30153, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (21049, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (46361, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (46212, 'Bricks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30350, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (94638, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (72475, 'Windscreens And Cockpits');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (60803, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (15714, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6227, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (44676, 'Signs, Flags And Poles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30008, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30244, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (93252, 'Figure, Weapons');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3794, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3245, 'Bricks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4536, 'Interior');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (92410, 'Interior');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (93140, 'Transportation Means, Vehicles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (21074, 'Figure Parts');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (26158, 'Figure Accessories, Upper And Lower Part');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30089, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30028, 'Tyres And Rims For Snap Ø3,2');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (59895, 'Tyres And Rims For Snap Ø3,2');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (92842, 'Transportation Means, Aviation');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (32013, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (44661, 'Transportation Means, Aviation');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (41879, 'Figure Parts');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (47755, 'Transportation Means, Vehicles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (15672, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (99207, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (25908, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (25960, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2460, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (25898, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (29219, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (24151, 'Transportation Means, Vehicles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2436, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4624, 'Tyres And Rims For Snap Ø3,2');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (74967, 'Tyres And Rims For Snap Ø3,2');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (24326, 'Wheel Base');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3673, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (98138, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (64288, 'Bricks, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4006, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4081, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (18228, 'Figure, Wigs');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (10126, 'Animals And Creatures');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (10127, 'Animals And Creatures');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (25901, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (33057, 'Foodstuff');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (11458, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (93590, 'Transportation Means, Vehicles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4871, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (50943, 'Transportation Means, Vehicles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (86208, 'Figure, Weapons');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (98397, 'Transportation Means, Vehicles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (88513, 'Animals And Creatures');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (92220, 'Figure Accessories, Upper And Lower Part');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (25956, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (32823, 'Figure, Head Clothing');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30010, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3035, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4070, 'Bricks, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (55978, 'Tyres And Rims For/To Snap Ø4,85 W. Cross');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (18971, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (28626, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (36452, 'Figure Accessories, Upper And Lower Body');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (45848, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (44873, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (44861, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3706, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (32316, 'Beams');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2723, 'Miscellaneous Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (11153, 'Bricks With Bows And Arches');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (28192, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (21019, 'Figure Parts');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3040, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (98835, 'Transportation Means, Vehicles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (47753, 'Bricks With Special Bows And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (31584, 'Transportation Means, Vehicles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (35480, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (45854, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (18395, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (40379, 'Animals And Creatures');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (45958, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (45962, 'Figure Parts');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (87747, 'Animals And Creatures');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (42798, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (32000, 'Bricks, Special Ø4.85 Hole And Connecting Bush');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (47457, 'Decoration Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3660, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3623, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30031, 'Transportation Means, Vehicles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (21712, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (15706, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (24201, 'Bricks With Bows And Arches');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (53540, 'Bricks, Special Ø4.85 Hole And Connecting Bush');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (42923, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (87083, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2654, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (98100, 'Bricks, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (11215, 'Bricks, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (14769, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (49563, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (42136, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (18863, 'Decoration Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (75937, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (35039, 'Animals And Creatures');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (79194, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (28624, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (34823, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (39223, 'Bricks, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (65886, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (35380, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (56145, 'Tyres And Rims For/To Snap Ø4,85 W. Cross');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (36083, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (33449, 'Figure Accessories, Upper And Lower Part');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2441, 'Wheel Base');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (45677, 'Transportation Means, Vehicles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (60481, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (88950, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4449, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (57783, 'Windscreens And Cockpits');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4865, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3822, 'Gates And Roofs');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3821, 'Gates And Roofs');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (92411, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4488, 'Wheel Base');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4208, 'Functional Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (87697, 'Tyres And Rims For Snap Ø3,2');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (86035, 'Figure, Head Clothing');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2445, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (74610, 'Rubbers And Strings');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (59714, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (45410, 'Bricks With Bows And Arches');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3029, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6091, 'Bricks With Bows And Arches');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (52501, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4162, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6231, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (73587, 'Signs, Flags And Poles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (50344, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (83484, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (44728, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4209, 'Functional Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (90194, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (64230, 'Tubes');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4176, 'Windscreens And Cockpits');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6014, 'Tyres And Rims For Snap Ø3,2');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (45411, 'Bricks With Bows And Arches');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (50745, 'Transportation Means, Vehicles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4533, 'Interior');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (52031, 'Transportation Means, Vehicles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (87087, 'Bricks, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (87609, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2496, 'Tyres And Rims, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2926, 'Wheel Base');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3068, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (32001, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (64644, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (95120, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2495, 'Wheel Base');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (42022, 'Bricks With Bows And Arches');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6081, 'Bricks With Bows And Arches');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (46413, 'Windscreens And Cockpits');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (59349, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (60032, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (89164, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (58380, 'Gates And Roofs');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (58381, 'Gates And Roofs');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (87552, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3027, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (46502, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4510, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30592, 'Bricks, Special Ø4.85 Hole And Connecting Bush');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30043, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (10313, 'Wheel Base');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (14682, 'Transportation Means, Vehicles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3065, 'Bricks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (86209, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (41532, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (41769, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (41770, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (32064, 'Bricks, Special Ø4.85 Hole And Connecting Bush');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (50304, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (50305, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6233, 'Bricks, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (60479, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (92584, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (87611, 'Transportation Means, Aviation');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3705, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (92582, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30386, 'Bricks, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (45936, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30387, 'Bricks, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30361, 'Bricks, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30367, 'Bricks, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4085, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4175, 'Decoration Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (15600, 'Figure, Head Clothing');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (32324, 'Bricks, Special Ø4.85 Hole And Connecting Bush');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (42608, 'Wheel Base');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30553, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (61483, 'Wheel Base');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (60470, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (42610, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2447, 'Figure, Head Clothing');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (87612, 'Transportation Means, Aviation');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3037, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (44572, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (82024, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (55068, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (87614, 'Transportation Means, Aviation');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (92279, 'Windscreens And Cockpits');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (87754, 'Figure, Head Clothing');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (87781, 'Figure, Head Clothing');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (93576, 'Transportation Means, Aviation');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3045, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (14718, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4345, 'Interior');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (26169, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (29380, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (40240, 'Figure, Wigs');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (36762, 'Figure, Wigs');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4332, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4495, 'Signs, Flags And Poles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (36752, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (68919, 'Figure Parts');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (48267, 'Decoration Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2450, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2462, 'Bricks, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (18980, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (39888, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (32607, 'Botanic');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3626, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (40289, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (41632, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (35381, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (32054, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3894, 'Bricks, Special Ø4.85 Hole And Connecting Bush');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4346, 'Interior');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (59443, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (87580, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (24855, 'Botanic');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (41239, 'Beams');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (10928, 'Functional Elements, Gear Wheels And Racks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (21725, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (33906, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (39341, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (39435, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (39445, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (39528, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3700, 'Bricks, Special Ø4.85 Hole And Connecting Bush');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (17715, 'Signs, Flags And Poles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (21462, 'Signs, Flags And Poles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (32524, 'Beams');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (42127, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3701, 'Bricks, Special Ø4.85 Hole And Connecting Bush');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4738, 'Interior');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (37697, 'Figure, Wigs');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (29336, 'Interior');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (44842, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (13670, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (25313, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (35388, 'Bricks, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (35294, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (49546, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (28661, 'Figure, Head Clothing');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (31922, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (76651, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2815, 'Tyres And Rims, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (49668, 'Decoration Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (26047, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (15070, 'Decoration Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (29119, 'Bricks With Bows And Arches');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (29120, 'Bricks With Bows And Arches');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (27261, 'Decoration Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (29111, 'Animals And Creatures');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (36806, 'Figure, Wigs');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2357, 'Bricks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (49307, 'Bricks With Bows And Arches');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (67886, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (93604, 'Transportation Means, Vehicles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (47456, 'Decoration Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (67841, 'Figure Parts');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (67638, 'Figure Parts');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2417, 'Botanic');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (42876, 'Foodstuff');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (14417, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (11214, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (33920, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (53127, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (67837, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6143, 'Bricks, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (14704, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2423, 'Botanic');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (13965, 'Bricks With Bows And Arches');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30099, 'Bricks With Bows And Arches');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (34283, 'Figure, Wigs');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (26601, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (23187, 'Figure, Wigs');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4498, 'Figure Accessories, Upper And Lower Body');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (60373, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (61537, 'Figure, Weapons');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30987, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (26604, 'Bricks, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (67839, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (37776, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3900, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (29167, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (28684, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (65720, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (75773, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (65509, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (18759, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (78171, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (15397, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (80675, 'Figure, Wigs');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (79571, 'Animals And Creatures');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (31570, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (88490, 'Figure, Head Clothing');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (67835, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (98011, 'Figure, Head Clothing');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (27263, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (28973, 'Bricks, Special Ø4.85 Hole And Connecting Bush');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (28961, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (28964, 'Bricks, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (95674, 'Figure, Head Clothing');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (61975, 'Figure, Weapons');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (38320, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (35391, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (53146, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (49153, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (44860, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (32474, 'Beams W/ Ball And Ball Cup');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6106, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (39616, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (24946, 'Foodstuff');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (37364, 'Figure Parts');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (33183, 'Foodstuff');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (24866, 'Botanic');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (31510, 'Miscellaneous Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (51270, 'Foodstuff');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (92947, 'Bricks, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (40244, 'Tubes');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (37784, 'Figure, Wigs');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (92746, 'Figure, Wigs');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3070, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3703, 'Bricks, Special Ø4.85 Hole And Connecting Bush');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3943, 'Bricks, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (60477, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (92946, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (18674, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (32952, 'Bricks, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (39759, 'Rubbers And Strings');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (20312, 'Animals And Creatures');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (20313, 'Animals And Creatures');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (39890, 'Rubbers And Strings');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (52738, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (38823, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (39777, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (53153, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (27150, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (17833, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (39772, 'Figure Parts');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (38628, 'Figure Accessories, Upper And Lower Part');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (38630, 'Figure Accessories, Upper And Lower Part');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (32807, 'Bricks With Bows And Arches');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3702, 'Bricks, Special Ø4.85 Hole And Connecting Bush');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (60808, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (11211, 'Bricks, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (50100, 'Animals And Creatures');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (65122, 'Functional Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (67324, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (40687, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3836, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (61780, 'Interior');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (60592, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (60594, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (95343, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (31561, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (28841, 'Decoration Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (35291, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (13564, 'Animals And Creatures');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (15462, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30565, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (29176, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (18754, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (15395, 'Bricks, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (98369, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (18041, 'Figure, Weapons');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (34173, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3837, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (65042, 'Figure, Weapons');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (38625, 'Electric Parts');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (37775, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4528, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (23986, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (37762, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (73983, 'Functional Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2444, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2488, 'Figure, Weapons');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (52107, 'Bricks, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (88072, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (91673, 'Figure, Head Clothing');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (45590, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3938, 'Functional Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (61678, 'Bricks With Bows And Arches');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (32039, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (88935, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2599, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (32123, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (94303, 'Figure Parts');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3048, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (55236, 'Figure Accessories, Upper And Lower Part');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2476, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2555, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (47759, 'Bricks With Slope, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6133, 'Animals And Creatures');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (41751, 'Bricks With Special Bows And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (93148, 'Figure Accessories, Upper And Lower Part');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6041, 'Transportation Means, Ships');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30088, 'Figure, Weapons');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (86500, 'Bricks, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (89159, 'Figure, Head Clothing');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4739, 'Interior');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (92290, 'Figure, Weapons');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30663, 'Transportation Means, Vehicles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (47455, 'Bricks, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (64450, 'Transportation Means, Vehicles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (91675, 'Figure Accessories, Upper And Lower Body');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (92692, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (33078, 'Foodstuff');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3737, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (32530, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (48170, 'Bricks, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (41531, 'Transportation Means, Aviation');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (94434, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (48169, 'Bricks, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (57909, 'Bricks, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (60208, 'Transportation Means, Aviation');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (60219, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4289, 'Transportation Means, Ships');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (93165, 'Loose Parts');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (94363, 'Figure Parts');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (92013, 'Bricks, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (55013, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3648, 'Functional Elements, Gear Wheels And Racks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6590, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (32073, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (33121, 'Animals And Creatures');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30150, 'Interior');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6587, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (87751, 'Transportation Means, Ships');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (89522, 'Animals And Creatures');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (64713, 'Miscellaneous Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (94355, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (92580, 'Windscreens And Cockpits');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30169, 'Animals And Creatures');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (44567, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2714, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (74698, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (54177, 'Body Shells');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30503, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6260, 'Figure Accessories, Upper And Lower Part');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6265, 'Figure Accessories, Upper And Lower Part');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6266, 'Figure Accessories, Upper And Lower Part');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30504, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (87617, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (96034, 'Figure, Head Clothing');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (95393, 'Figure Parts');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (93618, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (53705, 'Figure, Weapons');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30176, 'Botanic');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (60779, 'Signs, Flags And Poles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30237, 'Bricks, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (54782, 'Bricks, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2458, 'Bricks, Special Ø4.85 Hole And Connecting Bush');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (60169, 'Rubbers And Strings');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (60475, 'Bricks, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (92690, 'Figure, Weapons');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (48723, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30374, 'Signs, Flags And Poles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (92547, 'Miscellaneous Elements');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (93055, 'Figure, Weapons');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (63286, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (11055, 'Signs, Flags And Poles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2877, 'Bricks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3747, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30173, 'Figure, Weapons');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30363, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (94351, 'Figure Accessories, Upper And Lower Body');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (32270, 'Functional Elements, Gear Wheels And Racks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (64871, 'Beams');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (93059, 'Figure, Head Clothing');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3030, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (93621, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (93622, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6232, 'Bricks, Special Ø4.85 Hole And Connecting Bush');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3008, 'Bricks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3028, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (92338, 'Rubbers And Strings');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3942, 'Bricks, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (43899, 'Figure, Weapons');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (32014, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (30137, 'Bricks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (63965, 'Signs, Flags And Poles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (87601, 'Gates And Roofs');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (60752, 'Figure, Weapons');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4497, 'Figure, Weapons');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (93674, 'Frames, Windows, Walls And Doors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (93058, 'Figure, Weapons');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (43898, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (92691, 'Foodstuff');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (93062, 'Figure Accessories, Upper And Lower Part');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (93270, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (93069, 'Figure Accessories, Upper And Lower Body');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (93061, 'Figure Accessories, Upper And Lower Part');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (93761, 'Figure Accessories, Upper And Lower Part');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (93751, 'Figure Parts');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4522, 'Figure Accessories In Hand');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3049, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (96121, 'Figure Accessories, Upper And Lower Body');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (42003, 'Beams, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (32269, 'Functional Elements, Gear Wheels And Racks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (92438, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (96718, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6589, 'Functional Elements, Gear Wheels And Racks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (93755, 'Figure Parts');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (64290, 'Beams');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2339, 'Bricks With Bows And Arches');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3036, 'Plates');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3738, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (32002, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (59426, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3685, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (62462, 'Connectors');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2921, 'Bricks, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (6079, 'Fences And Ladders');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2449, 'Bricks, With Slope');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (88811, 'Figure, Weapons');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (54196, 'Plates, Special Circles And Angles');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (64647, 'Figure, Head Clothing');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (3633, 'Fences And Ladders');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (93763, 'Figure Accessories, Upper And Lower Part');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (96044, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4595, 'Plates, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2453, 'Bricks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (93746, 'Figure Parts');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (60583, 'Bricks, Special');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (93619, 'Figure, Heads And Masks');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (2489, 'Interior');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (44658, 'Figure, Weapons');
INSERT INTO lego_categories (id_LEGO_Categorie_Impose, nom_LEGO_Categorie)VALUES (4499, 'Figure, Weapons');