INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Black');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Bright Yellow');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Dark Stone Grey');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Transparent Brown');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Transparent Fluorescent Reddish Orange');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Transparent Red');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Transparent Yellow');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Brick Yellow');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Medium Stone Grey');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Transparent Blue');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Transparent Bright Orange');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Bright Blue');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Bright Green');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Bright Orange');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Bright Purple');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Bright Red');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Bright Yellowish Green');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Flame Yellowish Orange');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Light Nougat');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Multicombination');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Transparent');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Transparent Light Blue');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('White');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Cool Yellow');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Earth Blue');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Light Royal Blue');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Medium Blue');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('New Dark Red');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Sand Yellow');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Silver Metallic');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Titanium Metallic');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Warm Gold');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Dark Green');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Medium Lilac');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Olive Green');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Reddish Brown');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Dark Orange');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Medium Nougat');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Transparent Bright Green');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Bright Bluish Green');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Dark Brown');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Silver Ink');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Gold Ink');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Earth Green');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Bright Reddish Violet');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Light Purple');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Medium Azur');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Sand Green');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Transparent Fluorescent Green');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Transparent Green');
INSERT INTO lego_couleurs (nom_LEGO_Couleur) VALUES ('Cool Silver, Diffuse');